routes/web.php
<?php

use App\Http\Controllers\ApiCheckController;
use App\Http\Controllers\ApiOutageController;
use App\Http\Controllers\CcpsCore\AuthController;
use App\Http\Controllers\CcpsCore\HomeController;
use App\Http\Controllers\DownloadedFileController;
use App\Http\Controllers\CcpsCore\AccountController;
use App\Http\Controllers\CcpsCore\ChannelVerificationController;
use Laravel\Horizon\Http\Controllers\HomeController as HorizonHomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('home', [HomeController::class, 'index']);

Route::group(['prefix' => 'account'], function () {
    Route::get('/', [AccountController::class, 'index'])->name('account');
    Route::get('/settings', [AccountController::class, 'settings'])->name('account.settings');
    Route::post('/settings', [AccountController::class, 'updateSettings'])->name('account.settings.update');
    Route::get('/profile', [AccountController::class, 'profile'])->name('profile.show');
    Route::get('/profile/edit', [AccountController::class, 'editProfile'])->name('profile.edit');
    Route::patch('/profile/', [AccountController::class, 'updateProfile'])->name('profile.update');

    Route::prefix('tokens')->name('account.tokens.')->group(function () {
        Route::get('/', [AccountController::class, 'tokens'])->name('index');
        Route::get('create', [AccountController::class, 'createToken'])->name('create');
        Route::post('/', [AccountController::class, 'storeToken'])->name('store');
        Route::get('{token}', [AccountController::class, 'editToken'])->name('edit');
        Route::patch('{token}', [AccountController::class, 'updateToken'])->name('update');
        Route::delete('{token}', [AccountController::class, 'revokeToken'])->name('revoke');
    });

    Route::group(['prefix' => 'notifications'], function () {
        Route::get('/', [AccountController::class, 'notifications'])->name('account.notifications.index');
        Route::get('/channels/create', [AccountController::class, 'createChannel'])->name('account.notifications.channels.create');
        Route::post('/channels/create', [AccountController::class, 'storeChannel'])->name('account.notifications.channels.store');
        Route::delete('/channels/{channel}', [AccountController::class, 'destroyChannel'])->name('account.notifications.channels.destroy');
        // Route::get('/channels/{channel}/resend-verification', [ChannelVerificationController::class, 'resend'])->name('account.notifications.channels.resend-verification');
        // Route::get('/channels/{channel}/verify', [ChannelVerificationController::class, 'verify'])->name('account.notifications.channels.verify');
        // Route::get('/channels/{channel}/test', [ChannelVerificationController::class, 'test'])->name('account.notifications.channels.test');

        Route::get('/configure', [AccountController::class, 'configure'])->name('account.notifications.configure');
        Route::post('/configure', [AccountController::class, 'configureSave'])->name('account.notifications.configure.save');
    });
});

Route::middleware('auth')->group(function () {
    Route::prefix('api-checks')->name('api-checks.')->group(function () {
        Route::get('/', [ApiCheckController::class, 'index'])->name('index');
    });

    Route::prefix('api-outages')->name('api-outages.')->group(function () {
        Route::get('/', [ApiOutageController::class, 'index'])->name('index');
        Route::get('/{outage}', [ApiOutageController::class, 'show'])->name('show');
    });

    Route::prefix('downloads')->name('downloads.')->group(function () {
        Route::post('/', [DownloadedFileController::class, 'store'])->name('store');
    });
});


// CCPS Core routes
Uncgits\Ccps\Support\Facades\CcpsCore::routes();

// For local auth
Auth::routes();

// Socialite - User Account OAuth Routes
Route::get('auth/{provider}', [AuthController::class, 'redirectToProvider'])->name('oauth');
Route::get('auth/{provider}/callback', [AuthController::class, 'handleProviderCallback'])->name('oauth.callback');

// Canvas Auxiliary Feed
include('aux/routes.php');

// SIS feed
include('sis/routes.php');

// Horizon override
Route::group([
    'prefix'     => 'horizon',
    'namespace'  => 'Laravel\Horizon\Http\Controllers',
    'middleware' => config('horizon.middleware', 'web'),
], function () {
    // Catch-all Route...
    Route::get('/{view?}', [HorizonHomeController::class, 'horizon'])->where(
        'view',
        '(.*)'
    )->name('horizon.index');
});

app/Models/ApiOutage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ApiOutage extends Model
{
    protected $guarded = [];
    public $timestamps = false;
    protected $dates = [
        'created_at',
        'resolved_at'
    ];

    // relationships

    public function api_status_checks()
    {
        return $this->hasMany(ApiStatusCheck::class);
    }

    // scopes

    public function scopeInEffect($query)
    {
        return $query->whereNull('resolved_at');
    }

    // accessors

    public function getStatusAttribute()
    {
        return is_null($this->resolved_at) ? 'in effect' : 'resolved';
    }

    public function getStatusIconAttribute()
    {
        return is_null($this->resolved_at) ? 'exclamation-triangle' : 'thumbs-up';
    }

    public function getStatusClassAttribute()
    {
        return is_null($this->resolved_at) ? 'danger' : 'success';
    }
}

app/Http/Controllers/ApiCheckController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\ApiStatusCheck;
use Uncgits\Ccps\Support\CcpsPaginator;

class ApiCheckController extends Controller
{
    public function index(Request $request)
    {
        $checks = ApiStatusCheck::orderBy('created_at', 'desc')->with('api_outage');

        if (!$request->has('all')) {
            $checks->take(250); // limit for efficiency
        }

        $checks = $checks->get();

        $checks = new CcpsPaginator($checks, null, $request->page ?? 1);
        return view('api-checks.index')->with(compact('checks'));
    }
}

resources/views/api-checks/index.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'API Status Checks | Index'
])

@section('content')
    {!! Breadcrumbs::render('api-checks.index') !!}
    <x-h1>API Status Checks</x-h1>
    <div class="flex">
        <div class="col">
			<x-p>An <strong>API Status Check</strong> is a regular activity wherein a simple call is made to the Canvas API. This is done to ensure that the API is still reachable, since use of the Canvas API is necessary for functionality of this application. If enough consecutive checks fail, the application will be disabled automatically.</x-p>
			@if (!request()->has('all'))
				<x-p><strong>Note</strong>: for performance reasons, by default only the most recent 250 status checks are shown. You can choose to see the entire list by using the "View All" button below.</x-p>
			@else
				<x-p><strong>Note</strong>: showing complete API Status Check history.</x-p>
			@endif
        </div>
    </div>
    <x-hr />
	@if ($checks->isNotEmpty())
		@if (request()->has('all'))
            <x-button href="{{ route('api-checks.index') }}" color="red" size="sm">
                <x-fas>redo</x-fas> Reset
            </x-button>
		@else
            <x-button color="blue" size="sm" href="{{ route('api-checks.index', ['all' => 'y']) }}">
                <x-fas>eye</x-fas> View all
            </x-button>
		@endif
        <x-table>
            <x-slot name="th">
                <x-th>Date / Time</x-th>
                <x-th>Status</x-th>
                <x-th>Message</x-th>
                <x-th>Related Outage</x-th>
            </x-slot>
            <x-slot name="tbody">
                @foreach ($checks as $check)
                    <x-tr>
                        <x-td>{{ $check->created_at }}</x-td>
                        <x-td class="text-{{ $check->status_class }}">
                            <i class="{{ $check->status_icon }}"></i>
                            {{ $check->up ? "up" : "down" }}
                        </x-td>
                        <x-td>{{ $check->message }}</x-td>
                        <x-td>
                            @if (!is_null($check->outage))
                                <x-a href="{{ route('api-outages.show', ['outage' => $check->outage]) }}">Outage {{ $check->outage->id }}</x-a>
                            @endif
                        </x-td>
                    </x-tr>
                @endforeach
            </x-slot>
        </x-table>
    @else
    	<x-p>No API Status Checks exist.</x-p>
    @endif
@endsection