routes/web.php
<?php

use App\Http\Controllers\ApiCheckController;
use App\Http\Controllers\ApiOutageController;
use App\Http\Controllers\CcpsCore\AuthController;
use App\Http\Controllers\CcpsCore\HomeController;
use App\Http\Controllers\DownloadedFileController;
use App\Http\Controllers\CcpsCore\AccountController;
use App\Http\Controllers\CcpsCore\ChannelVerificationController;
use Laravel\Horizon\Http\Controllers\HomeController as HorizonHomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('home', [HomeController::class, 'index']);

Route::group(['prefix' => 'account'], function () {
    Route::get('/', [AccountController::class, 'index'])->name('account');
    Route::get('/settings', [AccountController::class, 'settings'])->name('account.settings');
    Route::post('/settings', [AccountController::class, 'updateSettings'])->name('account.settings.update');
    Route::get('/profile', [AccountController::class, 'profile'])->name('profile.show');
    Route::get('/profile/edit', [AccountController::class, 'editProfile'])->name('profile.edit');
    Route::patch('/profile/', [AccountController::class, 'updateProfile'])->name('profile.update');

    Route::prefix('tokens')->name('account.tokens.')->group(function () {
        Route::get('/', [AccountController::class, 'tokens'])->name('index');
        Route::get('create', [AccountController::class, 'createToken'])->name('create');
        Route::post('/', [AccountController::class, 'storeToken'])->name('store');
        Route::get('{token}', [AccountController::class, 'editToken'])->name('edit');
        Route::patch('{token}', [AccountController::class, 'updateToken'])->name('update');
        Route::delete('{token}', [AccountController::class, 'revokeToken'])->name('revoke');
    });

    Route::group(['prefix' => 'notifications'], function () {
        Route::get('/', [AccountController::class, 'notifications'])->name('account.notifications.index');
        Route::get('/channels/create', [AccountController::class, 'createChannel'])->name('account.notifications.channels.create');
        Route::post('/channels/create', [AccountController::class, 'storeChannel'])->name('account.notifications.channels.store');
        Route::delete('/channels/{channel}', [AccountController::class, 'destroyChannel'])->name('account.notifications.channels.destroy');
        // Route::get('/channels/{channel}/resend-verification', [ChannelVerificationController::class, 'resend'])->name('account.notifications.channels.resend-verification');
        // Route::get('/channels/{channel}/verify', [ChannelVerificationController::class, 'verify'])->name('account.notifications.channels.verify');
        // Route::get('/channels/{channel}/test', [ChannelVerificationController::class, 'test'])->name('account.notifications.channels.test');

        Route::get('/configure', [AccountController::class, 'configure'])->name('account.notifications.configure');
        Route::post('/configure', [AccountController::class, 'configureSave'])->name('account.notifications.configure.save');
    });
});

Route::middleware('auth')->group(function () {
    Route::prefix('api-checks')->name('api-checks.')->group(function () {
        Route::get('/', [ApiCheckController::class, 'index'])->name('index');
    });

    Route::prefix('api-outages')->name('api-outages.')->group(function () {
        Route::get('/', [ApiOutageController::class, 'index'])->name('index');
        Route::get('/{outage}', [ApiOutageController::class, 'show'])->name('show');
    });

    Route::prefix('downloads')->name('downloads.')->group(function () {
        Route::post('/', [DownloadedFileController::class, 'store'])->name('store');
    });
});


// CCPS Core routes
Uncgits\Ccps\Support\Facades\CcpsCore::routes();

// For local auth
Auth::routes();

// Socialite - User Account OAuth Routes
Route::get('auth/{provider}', [AuthController::class, 'redirectToProvider'])->name('oauth');
Route::get('auth/{provider}/callback', [AuthController::class, 'handleProviderCallback'])->name('oauth.callback');

// Canvas Auxiliary Feed
include('aux/routes.php');

// SIS feed
include('sis/routes.php');

// Horizon override
Route::group([
    'prefix'     => 'horizon',
    'namespace'  => 'Laravel\Horizon\Http\Controllers',
    'middleware' => config('horizon.middleware', 'web'),
], function () {
    // Catch-all Route...
    Route::get('/{view?}', [HorizonHomeController::class, 'horizon'])->where(
        'view',
        '(.*)'
    )->name('horizon.index');
});

app/Models/ApiOutage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ApiOutage extends Model
{
    protected $guarded = [];
    public $timestamps = false;
    protected $dates = [
        'created_at',
        'resolved_at'
    ];

    // relationships

    public function api_status_checks()
    {
        return $this->hasMany(ApiStatusCheck::class);
    }

    // scopes

    public function scopeInEffect($query)
    {
        return $query->whereNull('resolved_at');
    }

    // accessors

    public function getStatusAttribute()
    {
        return is_null($this->resolved_at) ? 'in effect' : 'resolved';
    }

    public function getStatusIconAttribute()
    {
        return is_null($this->resolved_at) ? 'exclamation-triangle' : 'thumbs-up';
    }

    public function getStatusClassAttribute()
    {
        return is_null($this->resolved_at) ? 'danger' : 'success';
    }
}

app/Http/Controllers/ApiOutageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\ApiOutage;
use Uncgits\Ccps\Support\CcpsPaginator;

class ApiOutageController extends Controller
{
    public function index(Request $request)
    {
        $outages = ApiOutage::orderBy('created_at', 'desc')->get();
        $outages = new CcpsPaginator($outages, null, $request->page ?? 1);
        return view('api-outages.index')->with([
            'outages' => $outages
        ]);
    }

    public function show(ApiOutage $outage)
    {
        $outage->load('api_status_checks');

        return view('api-outages.show')->with([
            'outage' => $outage
        ]);
    }
}

resources/views/api-outages/index.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'API Outages'
])

@section('content')
	{!! Breadcrumbs::render('api-outages.index') !!}
    <x-h1>API Outages</x-h1>
    <div class="flex">
        <div class="col">
            <x-p>An <strong>API Outage</strong> occurs when enough consecutive API Status Checks fail. (The threshold is configurable in Feed Settings.) During an API Outage the primary Cron Jobs controlling both the User Feed and Canvas Auxiliary Feed are disabled. Once the application determines that the API is reachable again, the Outage will be resolved automatically, and the Cron Jobs reactivated.</x-p>
        </div>
    </div>
    <x-hr />
    @if ($outages->isNotEmpty())
        <x-table>
            <x-slot name="th">
                <x-th>ID</x-th>
                <x-th>Created At</x-th>
                <x-th>Resolved At</x-th>
                <x-th>Status</x-th>
                <x-th># of Checks</x-th>
                <x-th>Actions</x-th>
            </x-slot>
            <x-slot name="tbody">
                @foreach ($outages as $outage)
                    <x-tr>
                        <x-td>{{ $outage->id }}</x-td>
                        <x-td>{{ $outage->created_at }}</x-td>
                        <x-td>{{ $outage->resolved_at }}</x-td>
                        <x-td class="text-{{ $outage->status_class }}">
                            <i class="fa fa-{{ $outage->status_icon }}"></i>
                            {{ $outage->status }}
                        </x-td>
                        <x-td>{{ $outage->api_status_checks->count() }}</x-td>
                        <x-td>
                            <x-button color="blue" size="sm" href="{{ route('api-outages.show', ['outage' => $outage]) }}">
                                <x-fas>list</x-fas> Details
                            </x-button>
                        </x-td>
                    </x-tr>
                @endforeach
            </x-slot>
        </x-table>
    @else
    	<x-p>No API Outages exist.</x-p>
    @endif
@endsection

resources/views/api-outages/show.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'API Outage ' . $outage->id
])

@section('content')
	{!! Breadcrumbs::render('api-outages.show', $outage) !!}
	<x-h1>API Outage {{ $outage->id }}</x-h1>
	<div class="flex">
		<div class="w-1/2">
            <x-card title="Status Information">
                <x-p><strong>Status</strong>:
                    <span class="text-{{ $outage->status_class }}">
                        <i class="fas fa-{{ $outage->status_icon }}"></i>
                        {{ $outage->status }}
                    </span>
                </x-p>
                <x-p><strong>Created at</strong>: {{ $outage->created_at }}</x-p>
                @if (!is_null($outage->resolved_at))
                    <x-p><strong>Resolved at</strong>: {{ $outage->resolved_at }}</x-p>
                @endif
            </x-card>
		</div>
		<div class="w-1/2">
            <x-card title="Contributing Status Checks">
                <x-ul>
                    @foreach ($outage->api_status_checks as $check)
                        <li>{{ $check->created_at }}</li>
                    @endforeach
                </x-ul>
            </x-card>
		</div>
	</div>
@endsection